### ISSUE TITLE
JIT detailed info

### ISSUE THREAD

**Issue by pgiraud** [dalibo/pev2#393]
We show JIT total time in the UI but without detail. In could be nice to show detailed information.

In plans, we can have info looking like:
```
JIT:
   Functions: 2
   Options: Inlining false, Optimization false, Expressions true, Deforming true
   Timing: Generation 0.244 ms, Inlining 0.000 ms, Optimization 0.121 ms, Emission 1.397 ms, Total 1.762 ms
```
